secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:nbqc0RKqA8AMvr5GyWv/RHVxb9iABFLizgPgsdylilvMoviFkBk=,iv:akP7TxyumxTQdEJ5YzhfGw+7Xrnpj5qEgBMJftw2MJ0=,tag:fnfWVDz5AEC8gtN/YHx8RA==,type:str]
    username: ENC[AES256_GCM,data:VPRbZOa0,iv:bX2KQ0LEsCLaPeZKR1yAdufr5NbGsC9rMCMZgm3pxVU=,tag:6bE5oTNadj85rtSz2gQqlQ==,type:str]
    password: ENC[AES256_GCM,data:aayBZ4hD3qZs3FUH,iv:bFHnCge72N2+++5kA859pnw06lBiRhfI7Wug+Ab0QLI=,tag:tpVsDG5ZYMaBBr1s/CFRSQ==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:OKmPof6/9GntWhPlXMG0zuUJAkrH9Iy5WQ==,iv:Aiqh9kh8iPdxZ58znOsKSY6+VLR+frtIRZihKgPugt8=,tag:wOj1i+fsgkSbB54kFTz4dA==,type:str]
    username: ENC[AES256_GCM,data:Vd6PIRVu,iv:RMz8Fk3kijZt6XBa4wT5IGFd5FdwTp3R0i8G3Fa4xOg=,tag:PFTeiZY3yoloovyO+9ar8Q==,type:str]
    password: ENC[AES256_GCM,data:mpqEN7+1q36s9m3I,iv:X7eBpqg0qz5Kbm06DB4y6aS+Of3EfrERYFED4XQufRE=,tag:wtvCsOo14IwKl+oiD2WuoQ==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:1RZ5CiasrKZeBgGk8GUVAygARfWhWON7qb707k/ut70AqklK7/pnFHMcGN33NlU57yXVaYdeKybmmM3/1IXDkA==,iv:I6RXbUw7JHIYmsmI6JieCkxViGQWNxgb/+QIyPsrXyM=,tag:5w6tgZvBgXB5Io+LdvzFVw==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:opexDq1sqgZNDihntsdvrAgSVmV/aw==,iv:u6dZYR/85AQuE5JgyAzn0weRJ70S0qn0FnKQAlLk8i8=,tag:NN1iBkzQ8cfx1iorQlVK4A==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:9kitFsS64eqo6pAIsGjFndfSeaRsesIfL1zuGZIlXFVOGu9vqxbGqg4Wt1f4amFTnNiJkr/klBgmZwBKIRw4hWxfEsUo4jcW1Zkes3mYYtI/LDi2+lM=,iv:aG5fCZpPEhafVdV47GpanU4Rnv5BnopX8Um3eIMlWL4=,tag:TiIH7bDbevV1RGZ39EcS1g==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:ofCd1NAiVBCz,iv:4Nx6JWakwXY2NBaJed+qufdAELwuJK5hnb0/zLxVhHA=,tag:usZAyuEqLX3LAAywdnWCDw==,type:str]
    password: ENC[AES256_GCM,data:CcgTpqeOyzq+FSsz,iv:vITY5tiEphimG75t2DFCeOstOFRPxvYHQQyEu4SA4BM=,tag:yEBn5WD5TNq/quH9O5o9cg==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:DAUYI0J1+4Mn,iv:KWZMZArKKOtU0wZ2uXp0taONdgUd/Dml9/UmcLtIqNs=,tag:vWyCbBIz3w+8JCGK8Ha6zw==,type:str]
    password: ENC[AES256_GCM,data:dnQEYWY94l1gb04F,iv:SJ/KF9lOzy4Q7FCs1njp/cL34tMXemKVojkH1zKZ1vk=,tag:WKkPUWl5+yunJLHa4y7h/A==,type:str]
    server_address: ENC[AES256_GCM,data:9tGVO8Ijz/YfmZFF7Ad5C9cY,iv:RQb781RfJwoUPWQcES6SHxI5qH/b6lZU3FKRLy7m5ms=,tag:AEpdJ4ggBDHpuZ/LDicblQ==,type:str]
secret_ethstats: ENC[AES256_GCM,data:AbQpKiPY3AkjiV1ztGkaOHV2OjJZA9N/RsKfPWj3SwFeZaAvoKo0Ch5H+3ZtYVS+gAhVuRHWcmIvzyKQH1UnNA==,iv:gN4TgZfvclYIBN9wGBrse8JJ2bbZevrE/CR4+Pt8Y50=,tag:MkjH5SUgtRO06cWZ2HikSg==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:sWg/yOEO/atq8q+gZcAXDwJdcSExXRqJXkQ4xmBrQ3lbThKaJH/NXTjRmCngwCefWFsm8+2miJj6kau8ZIWuOue82yb5pdo8/lvIxpYsQQPtpHX22qzOH00/ZXtPAqPj/vF/fEq8xqfXhHdY3z1xRDlXvd6FNdgdYk5XUVxlaGyH35LUiwoytxO2y/sdrpgAj8Tb,iv:LVWCgTRlVjvFPhUFWGRnUHADqdZHCB1RXRQE4Lv2tlU=,tag:xxdKRUvMw/M3tU16l+NACA==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:dqOpL4LCpNPL1DMFMEY5/YYDxizZAEpH69+7AP+0FRVF7FzwN6J04+vVzDA971Q9d6YbNfhHbJR9jj4gXBipj38pEFwI7OMAUYUq73KaSFPhF8zjDHFdWqRamW95dKAxbBTmTv/PfW+VOhd5IOpkLIxPaGdPiDTMrngBeawFRTKnjqc66HS/hX0sPpM0U9sMm6x7zKM=,iv:taI3ysLkI/FCqfMyIWv7Crt88fVMzoMMFxFUAk99QGo=,tag:pbL+EexiEFS1UeFFsL8R/w==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:vBDwsIT/GsaKzRj3NczFI5TiOqJvkMmgb6kqvtAXIxdvlluBSAZyD8S3tWVzzNgg2f+WbFGgx4WMl0qYAm/ZlQ==,iv:9zgLfBwgu6JEGBZTBZ1MI3I1dScawZN/IqSeskFgD5w=,tag:qjIAoLBpzVFLKzP4vfH44g==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:ZGf6sSj0DvMiFXR7JVqLmBXoTWzm1tgLef2jJFjBzgZiSk/Jb2+MyG0v6elgIMFVsY86/G4wNy1zunKbsP1gaA==,iv:Qq1s5GVo0J0Y/CVHEvRPVpWxBnsn/vAzQNVgmNgoTo0=,tag:mW+Vw2ODk7OlOCEBVy/NNA==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:n89GXRGqJhgc0y7TLhhq06y5Q6Nb5g4HX91Y476qAX/KpUGTFXjwNq1ItUogBDeRajLvdXIgrYC72ZpodBxuWA==,iv:W+h5JgBFNRjeQSWDd98F0nMWxHrMdaIaKdbsUMVDHhU=,tag:SDfAp4eTjZxKvrq/feKq8A==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:cPc6z4jGPNTLxlKTSuC+iJJOZ1pAHNyWEqTloashBLEIwwoMtB1AQLXGg//qWePY5/y19Zudpx7MlRZWvJAtMw==,iv:ZZsRKhAhaWHgovXRRbmVXrFQIHlrldfsWoTy9YW7D70=,tag:e4TsywWxAMnNu643XxMMWw==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:GRyaWq3dSFaG,iv:xBaT3SsI/n+nFbiQLHmdclCAQ1l4KBVZtycV6EnIz4A=,tag:mwnpMdUEPW/CtO8DZtlECA==,type:str]
goomy_private_key: ENC[AES256_GCM,data:BVvji6tHhjszQ84FPPMRKI42WWtuICr51xVRxqS97L44lZZ2mR8advHLnPNBiD8wn9KWrsjP4wS7jZdpfQ8C7Q==,iv:dGscGSWouhn8MmMYX0sDLHZMCxTLYsCUVH7BBq6CFDI=,tag:RQDNGGpx1c+U4roJrab5oA==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:to24WZ5iFvzpWRZfQtH7Wy64HUdba0R0vRiKBjUDuS0rhrzdZTviNcphouDq4LSK/bbvkSIYMXVKNY9R5d4XfQ==,iv:rhdK3uevK2inqoc/mIrmAW3vfHvb13Njdf6VwFHUWGE=,tag:Z9AQIFQ2xKlowdB6ryUlAw==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:giN4+cj/+Uwg,iv:D4l98FvEKCws4iBwQRIm+NlHWijfgnRl/xF2sLsw1ZQ=,tag:wg5Q6SjPOcXS94PSyOvCfg==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:zpNolMMvdcuKmeaI,iv:mRq0xUH6fjbqvePqQbCWSPnnIT41lnX+hMvGlEpD14Y=,tag:6AEtornJPZClAwu74ZrBFg==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:KuQhgxQ2GCj9PqEa8bhmkt1aRg8Wb1VlBOENhgmUN1TEU4RIaeaGBYvgDNK9I1PEgvfq/obg5SN0hu9gGdyk6w==,iv:h67Qe7YBRLq6WqBKeqA4jH0T0EcSSsV8X8UshQIUmP0=,tag:2h08oeajMoe0IHkKUTBvuQ==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:l6c4OtDIHdY2iheI,iv:OfSj4CHbrGjz7cSn5l7xtP4YfB3EiPONG2x9PNro5xE=,tag:eu1myKo3eFlqFwKsLD3YXA==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:+Q6hddHU8d2L,iv:WQHag7SfoIrGmk3Fk8TBb4/DphbMmB1U/Vnv1ijkmhQ=,tag:peAzw1RsjGOu5IwlDoKyRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-10T04:15:16Z"
    mac: ENC[AES256_GCM,data:1fwlBcM5Hqhp1aOdhGIQSwohtlLhMn5OrgxDs2N4cA1kNR5LjFKvktUG7P3YhHQookJc6u06wDbRFD/OhBV39/Azoyha2oAUGLe/gQ8r5NYe0VO91BtDnKDsYJ06HQR8A2Xkg6JFHF+OW4y/0VCudx0GKZ0vBI+NIgMqx5KTt1o=,iv:9i9jud1GtVgkvCPPi3h+C3QCIEGqyhvurgniI2pGza4=,tag:sExmZcdpK8DBddGS+FV05A==,type:str]
    pgp:
        - created_at: "2025-03-10T04:15:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxSt+6D25TJ5ARAAz14MFaqLLEhrdoBoJZai8eq39wYzTO5bthbtRK/UJFUV
            lmBFZtnFZ7UThNwsmfJ3KWcDV+UfnEw6aYeYoRVWGSyUikC3QRVYWx5edoM/1dzG
            IOvextlWXu0gJs8pFFBVBBShDBkH5mAZdEKYGyKyfiBUkf2bCc4MVLLY5hoTT8o/
            v2stZhZU7fwTTMNxDVzyPA4Mf2yQfxv2ysp4p3IOA6M0ypPdoxgbpKVc3c6IFdXA
            jWRrPLVkKXhVMmuRmD7SgeK2bmXMmyLvNrU1FbfPEmQMXuGOXbl8OeoDIjH0lJcl
            BCMgYLFQCX87muNIzQkPpoWoLPu6288cljPQ/cEu1/aj+uXB/NEr4BKptjYCS50K
            YVsV6aaD1sIBDLUHvRLL+OEhpMDWZl369GwhYK3vQT5p25fwTeeVltDDSNcpWB1p
            g0v7jdwITv2xte8zHjE7G4zdvkE0Z+4/H0TV5dt4zz/7iqNzs/FeuGgc2mpRdmA3
            BBSyTi1ybaPTaLizpvV4BgwH9fNvg9MqxIhg71ntZviuSRhEWB2+4JEKiCuYiRC8
            LIDtHTVL3M019LqmMGy3xnZEdL7bmPJRozFqPA9eYFPdJMzU4HWdRzvkH+ZzyiOo
            QgbJwkmnhxQ/VMrlb4ijFUcjMiyZLJCdqKhD5JYHOZt7w3vMF/ALm1TC+m+OSn7U
            aAEJAhBtO0c5ZJwM0ND/nwOPZIlPtX3mZZNEPs2FEHrYBsj76CTJ318pLo83/sS9
            06TfJ0NWxL6oOzUqVbPYXWE4IxjXXu5CFCAUiaQtZgl9ex4nWa/+gW6NmVMKtWJv
            mc1PWSTpyYJz
            =uxgT
            -----END PGP MESSAGE-----
          fp: FFA8015BD6212E579B3813B78DC0A30AA95F49A1
    unencrypted_suffix: _unencrypted
    version: 3.9.4
