default_ethereum_client_images:
### Consensus layer clients
  lighthouse: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:unstable-476f3a593
  lighthouse_validator: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:unstable-476f3a593
  lodestar: docker.ethquokkaops.io/dh/ethpandaops/lodestar:peerDAS-5cd8ace127
  nimbus: docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth2:getBlobsV2-f56416d
  prysm: docker.ethquokkaops.io/dh/ethpandaops/prysm-beacon-chain:peerDAS-linux-amd64-eeb3cdc
  prysm_validator: docker.ethquokkaops.io/dh/ethpandaops/prysm-validator:peerDAS-linux-amd64-eeb3cdc
  teku: docker.ethquokkaops.io/dh/ethpandaops/teku:nashatyrev-das-7109573
  grandine: docker.ethquokkaops.io/dh/ethpandaops/grandine:hangleang-peerdas-devnet-6-minimal-97017f9
### Execution layer clients
  besu: docker.ethquokkaops.io/dh/hyperledger/besu:latest
  geth: docker.ethquokkaops.io/dh/ethpandaops/geth:marius-engine-getblobs-v2
  erigon: docker.ethquokkaops.io/dh/thorax/erigon:devel
  ethereumjs: docker.ethquokkaops.io/dh/ethpandaops/ethereumjs:master
  nethermind: docker.ethquokkaops.io/dh/ethpandaops/nethermind:feature-peerdas
  reth: docker.ethquokkaops.io/dh/ethpandaops/reth:rkrasiuk-peerdas

default_tooling_images:
  xatu_sentry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  ethereum_metrics_exporter: docker.ethquokkaops.io/dh/ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: docker.ethquokkaops.io/dh/ethpandaops/tx-fuzz:pr-56
  forkmon: docker.ethquokkaops.io/dh/skylenet/nodemonitor:darkmode
  forky: docker.ethquokkaops.io/dh/ethpandaops/forky:latest
  fauceth: docker.ethquokkaops.io/dh/skylenet/fauceth:fix_fee_estimation
  powfaucet: docker.ethquokkaops.io/dh/pk910/powfaucet:v2-stable
  ethstats: docker.ethquokkaops.io/dh/skylenet/ethstats-server:poa-no-geoip
  homepage: docker.ethquokkaops.io/dh/ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: docker.ethquokkaops.io/dh/ethpandaops/checkpointz:0.0.12-electra
  blockscout: docker.ethquokkaops.io/dh/blockscout/blockscout:latest
  blockscout_frontend: docker.ethquokkaops.io/gh/blockscout/frontend:latest
  beacon_metrics_gazer: docker.ethquokkaops.io/dh/dapplion/beacon-metrics-gazer:latest
  eth_fauceth: docker.ethquokkaops.io/dh/chainflag/eth-faucet:latest
  blobscan: docker.ethquokkaops.io/dh/blossomlabs/blobscan:latest
  blobscan_indexer: docker.ethquokkaops.io/dh/blossomlabs/blobscan-indexer:latest
  dora: docker.ethquokkaops.io/dh/ethpandaops/dora:fulu-support
  goomy: docker.ethquokkaops.io/dh/ethpandaops/goomy-blob:master
  dugtrio: docker.ethquokkaops.io/dh/ethpandaops/dugtrio:latest
  ethereum_genesis_generator: docker.ethquokkaops.io/dh/ethpandaops/ethereum-genesis-generator:4.0.2
  tracoor: docker.ethquokkaops.io/dh/ethpandaops/tracoor:0.0.26-debian
  ncli: docker.ethquokkaops.io/dh/status-im/nimbus-eth2:unstable
  lcli: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:unstable-a94b12blo
  zcli: electra
  assertoor: docker.ethquokkaops.io/dh/ethpandaops/assertoor:master-latest
  erpc: docker.ethquokkaops.io/gh/erpc/erpc:main
  prometheus: docker.ethquokkaops.io/dh/prom/prometheus:v2.40.7
  node_exporter: docker.ethquokkaops.io/dh/prom/node-exporter:v1.5.0
  cl_bootnode: docker.ethquokkaops.io/dh/protolambda/eth2-bootnode:cleanup
  json_rpc_snooper: docker.ethquokkaops.io/dh/ethpandaops/json-rpc-snoop:1.1.0
  nginx_proxy: docker.ethquokkaops.io/dh/nginx:alpine
  nginx_proxy_gen: docker.ethquokkaops.io/dh/nginxproxy/docker-gen
  nginx_proxy_acme: docker.ethquokkaops.io/dh/nginxproxy/acme-companion
  vector: docker.ethquokkaops.io/dh/timberio/vector:0.30.0-alpine
  spamoor: docker.ethquokkaops.io/dh/ethpandaops/spamoor:blob-v1-latest
  xatu_cannon: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest