# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: peerdas-devnet-ssl-1
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        peerdas-devnet-ssl-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.peerdas-devnet-ssl-1.yolkie.xyz
    clientArgs:
      networks:
        peerdas-devnet-ssl-1:
          execution:
            besu:
            nethermind:
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7093422581
              - --syncmode=full
              - --bootnodes=enode://838cc2fe322a83e8b81a13cfb245a37f26e97d6e2356e105f7bb98377b394a59b450516c2e8f490b4de7770811080749912324484b1f528d67f598382aac6f10@68.183.139.143:30303?discport=30303,enode://e886ee77c0f0a47e06afc7e6d73ac327fff9fe2c441679014f0d39b6cc57331a557fcdb77163d81440775b56fb41b043c8279f01d42e8d2455eecd36e22960e6@68.183.129.66:30303?discport=30303,enode://6281b653771afb26cc87d525bba27bfbdf9c3bf7eb83e8753e1b9d19cef03cb6ff916091307fe63d1055e496f89e773f7ffc792b62d64630dcd815e3add26007@67.205.173.103:30303?discport=30303,enode://abbe90f7287f0d0153bd411b49f0ad5c43ced38e2ae52025e5d7f14933569322ddf78d4b8f244c5365dddcba4ab98231d961fd1b7aa595f8f7c027f61acd3b9e@146.190.104.223:30303?discport=30303,enode://37b58d5769e8aed881b804d3e294eb1895f06d181d51d4a86d21f2109f9b7c4eda00a895438c593e91d53341f8cc01e84184e81960e471bbe1eba72aa3e5f604@134.209.22.55:30303?discport=30303,enode://e5b6b4e83a0467e3f68b83017fe839d7b905ff2b146d4177cc77ac301ef130f9a80fe63f9740ee7fb5d67426c118a57de88ee1cba69381e54a07991ab82a9ae5@165.227.181.193:30303?discport=30303,enode://3992908db63066930881f4cc8d513dd45f22e3639717a62ec164a9a6871def9846089db82c7632dfa143f9653cf72693bf4fb4f92cd45a4b2c047283ab8949f2@167.99.147.246:30303?discport=30303,enode://7a7444879c6cb7558e9c6e262e35562a2684c23dd9e5e7ee36101ec2676ce9d84389ec7037c6b54c222db6923153ea290f1537ee1aa19c5b4457da7292d243f8@159.223.86.37:30303?discport=30303,enode://050eb075260a556a5fd4f3ea1c92c15092dc903724adeda412b7dfd6af5dd11a6b15f024ff80929633904dd02828dbaa0526b7797273da7a6f7499cd1687ba76@188.166.147.174:30303?discport=30303,enode://ecc8a660975f67cafbdee1aa7b8406048cc31e987032dd471ec5e194c6e6304eb8128ab0ce5278ffa13e94c7983b599e3207a1af6b0b020cff8028eaa371d005@104.236.211.168:30303?discport=30303,enode://9f3c6969476d834d80ee208c7f70175b4ea163ac16f15d6d82b732b15deb38ef43dcc6d4274815c26ac2cfe18145237c2a6ecf310d84857b768374ccbab61c66@209.38.36.171:30303?discport=30303,enode://ed6a00f73427b297aac84a47c055f9596e5c67d1d864f69485a3e50f0101a9d961a09e289115162f8a7dfff5afb106c4c55568a8559e66555058d55df0595349@67.205.130.45:30303?discport=30303,enode://6184caa59c8bd8af618fdb42d4e50f703ea607b187bd59aa5de5990649d62f648424d9dc1560d1397e0a8d1e5ab340234b3ccf7b50de32e474d1c7c3d7f89028@178.128.26.153:30303?discport=30303,enode://5d1547edce6122417cb2908fb3410cb423d7ad306250d0dc23178da8f089a7d065a41cb614358876a3a70dbcef1be643fd4e322ce676e1af3337399c26c14277@134.209.31.94:30303?discport=30303,enode://a8e5a871e05bdb71920560938041116383ed2a91720913fb7ae55ceeb7b6f4fe03e3cdc050716ab4e8a76781a71f24b0bcbf0168404622c6b7f38ec3048824a1@104.236.225.177:30303?discport=30303,enode://16f195496e93d9edc1270a3a4a4cb95ff6b0cda6513f811e771424d0204954173a46765270947ee37b01410b2b2f6d5ec1f6de4750e032b14c7ab1b81f9b0d88@134.209.94.100:30303?discport=30303,enode://3a1818bcd650f1aacfc2a54b0ecbb91324b9724d189b4a11150d722151dbc5282a4fa293a8c9e70834c06e5ec19469682d6f4e0196d71c233116b8112b0a52df@192.241.136.120:30303?discport=30303,enode://54b315fbf409e597ec9c17eb171d9b5af77792c88f5eff4bcefb0c9b7b34783e5122760321c8be9366b28f074cbfe4c71038e91044ec402e1a03ceebd31b35e8@157.230.33.148:30303?discport=30303,enode://2bef8a73c53c567966364e317fbebaca71b079b18c761cacf752e8f206a791aa4a0b8ad573aea00df522dc362efe5f2feec72d1cad795a8d059938c11642eed8@188.166.156.92:30303?discport=30303,enode://bfd0d59b7f372520e9cce159b966236a96063333050d60bab87f727ac366c42ccf7262031d545d3423852da72257a154b5a48ceb8142664f0733576043efdc35@104.236.212.192:30303?discport=30303,enode://cf982acaebd5d3a37a8bcf8b6e78d0c3d8f64a63adcfa4ba742ae04fffb40abb074d3c1a7a1628c9ffa10bd4192a4fcbaad4b8e22c849bff8800afb143011fa1@134.209.95.187:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.ethstats_secret}>@ethstats.peerdas-devnet-ssl-1.yolkie.xyz
              - --rpc.allow-unprotected-txs
            erigon:
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QPsRSQZbuq6DK2p2C5VVcMME475-dR3grcDcEa-ibk3PcCGYl87dYGC1sDvbdixcvbUfEtorgstYYnooLWMGnpWGAZWKxvWbgmlkgnY0gmlwhES3i4-Jc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-OO4QATbVzLN8Rti-hPbLO6Z8QNel7trJA8QuERR5bu2V94LHSZdE8BDlhFN-_o3wRkJ4D6dtFf9iiStVYemODlmi6UDh2F0dG5ldHOIAAAAgAEAAACDY2djgYCGY2xpZW500YpMaWdodGhvdXNlhTYuMC4xhGV0aDKQ1j-F32B1FzgBAAAAAAAAAIJpZIJ2NIJpcIREt4uPhHF1aWOCIymJc2VjcDI1NmsxoQJo-AynnBA9bArGcRUQpEnTveIYtR6AQ22bO0LRz8rIwIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --persistNetworkIdentity
              - --logLevel=debug
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QPsRSQZbuq6DK2p2C5VVcMME475-dR3grcDcEa-ibk3PcCGYl87dYGC1sDvbdixcvbUfEtorgstYYnooLWMGnpWGAZWKxvWbgmlkgnY0gmlwhES3i4-Jc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-OO4QATbVzLN8Rti-hPbLO6Z8QNel7trJA8QuERR5bu2V94LHSZdE8BDlhFN-_o3wRkJ4D6dtFf9iiStVYemODlmi6UDh2F0dG5ldHOIAAAAgAEAAACDY2djgYCGY2xpZW500YpMaWdodGhvdXNlhTYuMC4xhGV0aDKQ1j-F32B1FzgBAAAAAAAAAIJpZIJ2NIJpcIREt4uPhHF1aWOCIymJc2VjcDI1NmsxoQJo-AynnBA9bArGcRUQpEnTveIYtR6AQ22bO0LRz8rIwIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --minimum-peers-per-subnet=1
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QPsRSQZbuq6DK2p2C5VVcMME475-dR3grcDcEa-ibk3PcCGYl87dYGC1sDvbdixcvbUfEtorgstYYnooLWMGnpWGAZWKxvWbgmlkgnY0gmlwhES3i4-Jc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-OO4QATbVzLN8Rti-hPbLO6Z8QNel7trJA8QuERR5bu2V94LHSZdE8BDlhFN-_o3wRkJ4D6dtFf9iiStVYemODlmi6UDh2F0dG5ldHOIAAAAgAEAAACDY2djgYCGY2xpZW500YpMaWdodGhvdXNlhTYuMC4xhGV0aDKQ1j-F32B1FzgBAAAAAAAAAIJpZIJ2NIJpcIREt4uPhHF1aWOCIymJc2VjcDI1NmsxoQJo-AynnBA9bArGcRUQpEnTveIYtR6AQ22bO0LRz8rIwIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QPsRSQZbuq6DK2p2C5VVcMME475-dR3grcDcEa-ibk3PcCGYl87dYGC1sDvbdixcvbUfEtorgstYYnooLWMGnpWGAZWKxvWbgmlkgnY0gmlwhES3i4-Jc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-OO4QATbVzLN8Rti-hPbLO6Z8QNel7trJA8QuERR5bu2V94LHSZdE8BDlhFN-_o3wRkJ4D6dtFf9iiStVYemODlmi6UDh2F0dG5ldHOIAAAAgAEAAACDY2djgYCGY2xpZW500YpMaWdodGhvdXNlhTYuMC4xhGV0aDKQ1j-F32B1FzgBAAAAAAAAAIJpZIJ2NIJpcIREt4uPhHF1aWOCIymJc2VjcDI1NmsxoQJo-AynnBA9bArGcRUQpEnTveIYtR6AQ22bO0LRz8rIwIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
              - --allow-insecure-genesis-sync
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --light-client-data-serve=false
              - --debug-peerdas-supernode=true
              - --sync-light-client=no
              - --bootstrap-node=enr:-Iq4QPsRSQZbuq6DK2p2C5VVcMME475-dR3grcDcEa-ibk3PcCGYl87dYGC1sDvbdixcvbUfEtorgstYYnooLWMGnpWGAZWKxvWbgmlkgnY0gmlwhES3i4-Jc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-OO4QATbVzLN8Rti-hPbLO6Z8QNel7trJA8QuERR5bu2V94LHSZdE8BDlhFN-_o3wRkJ4D6dtFf9iiStVYemODlmi6UDh2F0dG5ldHOIAAAAgAEAAACDY2djgYCGY2xpZW500YpMaWdodGhvdXNlhTYuMC4xhGV0aDKQ1j-F32B1FzgBAAAAAAAAAIJpZIJ2NIJpcIREt4uPhHF1aWOCIymJc2VjcDI1NmsxoQJo-AynnBA9bArGcRUQpEnTveIYtR6AQ22bO0LRz8rIwIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/geth
      tag: PeerDAS-7f6090b
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31947
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: peerdas-devnet-ssl-1
      testnet: peerdas-devnet-ssl-1
      ethereum_network: peerdas-devnet-ssl-1
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/el/chainspec.json;
            GENESIS_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/el/genesis.json;
            BESU_GENESIS_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/el/besu.json;
            ENODES_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethpandaops/geth:PeerDAS-7f6090b
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/teku
      tag: nashatyrev-das-7109573
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32636
    podLabels:
      network: peerdas-devnet-ssl-1
      testnet: peerdas-devnet-ssl-1
      ethereum_network: peerdas-devnet-ssl-1
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.peerdas-devnet-ssl-1.yolkie.xyz/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.peerdas-devnet-ssl-1.yolkie.xyz/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
