# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dugtrio.yaml.j2

dugtrio:
  fullnameOverride: dugtrio
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dugtrio
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: beacon.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  dugtrioFrontendTitle: "Dugtrio: pectra-devnet-ssl-lighthouse-1"
  dugtrioProxyCount: 2
  dugtrioProxyBlockedPaths:
    - "^/teku/v[0-9]+/admin/.*"

  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.bootnode-1.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: bootnode-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-10.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-10
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-11.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-11
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-12.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-12
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-13.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-13
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-14.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-14
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-15.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-15
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-16.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-16
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-17.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-17
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-18.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-18
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-19.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-19
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-2.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-2
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-20.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-20
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-21.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-21
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-22.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-22
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-23.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-23
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-24.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-24
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-25.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-25
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-26.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-26
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-27.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-27
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-28.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-28
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-29.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-29
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-3.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-3
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-30.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-30
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-31.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-31
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-32.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-32
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-33.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-33
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-34.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-34
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-35.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-35
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-36.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-36
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-37.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-37
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-38.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-38
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-39.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-39
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-4.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-4
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-40.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-40
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-41.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-41
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-42.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-42
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-43.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-43
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-44.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-44
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-45.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-45
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-46.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-46
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-47.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-47
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-48.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-48
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-49.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-49
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-5.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-5
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-50.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-50
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-6.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-6
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-7.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-7
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-8.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-8
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-9.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-9
