# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/forkmon.yaml.j2

forkmon:
  fullnameOverride: forkmon
  image:
    repository: docker.ethquokkaops.io/dh/skylenet/nodemonitor
    tag: darkmode
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: forkmon.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix
  network: pectra-devnet-ssl-lighthouse-1
  endpoints:
  # Rpc
  - addr: http://geth-teku-001:8545
    name: rpc-teku-geth-001
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: bootnode-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-10.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-10
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-11.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-11
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-12.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-12
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-13.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-13
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-14.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-14
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-15.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-15
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-16.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-16
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-17.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-17
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-18.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-18
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-19.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-19
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-2.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-20.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-20
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-21.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-21
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-22.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-22
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-23.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-23
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-24.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-24
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-25.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-25
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-26.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-26
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-27.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-27
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-28.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-28
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-29.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-29
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-3.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-3
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-30.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-30
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-31.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-31
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-32.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-32
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-33.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-33
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-34.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-34
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-35.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-35
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-36.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-36
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-37.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-37
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-38.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-38
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-39.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-39
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-4.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-4
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-40.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-40
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-41.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-41
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-42.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-42
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-43.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-43
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-44.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-44
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-45.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-45
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-46.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-46
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-47.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-47
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-48.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-48
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-49.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-49
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-5.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-5
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-50.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-50
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-6.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-6
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-7.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-7
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-8.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-8
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-9.pectra-devnet-ssl-lighthouse-1.yolkie.xyz
    name: lighthouse-geth-9

  config: |
    # How often to reload data from the nodes
    reload_interval = "10s"
    # If specified, a http server will serve static content here
    server_address = "0.0.0.0:{{ .Values.httpPort}}"
    # Shown in the document title, if specified
    chain_name="{{ .Values.network }}"
    # Local or non third party connection require rpc kind
    {{- range .Values.endpoints }}
    [[clients]]
      url  = {{ .addr | quote }}
      name = {{ .name | quote }}
      kind = "rpc"
    {{- end }}
