# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/erpc.yaml.j2

erpc:
  fullnameOverride: erpc
  image:
    repository: docker.ethquokkaops.io/gh/erpc/erpc
    tag: main
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: rpc.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  config: |
    logLevel: info

    database:
      evmJsonRpcCache:
        connectors:
          - id: memory-cache
            driver: memory # Refer to "memory" driver docs below
            memory:
              maxItems: 100000
        policies:
          # Cache all methods with finalized data including empty responses
          - network: "*"
            method: "*"
            finality: finalized
            empty: allow
            connector: memory-cache
            ttl: 0
          # Cache unfinalized data only for 5 seconds (getLogs of a recent block) except empty responses
          - network: "*"
            method: "*"
            finality: unfinalized
            empty: ignore
            connector: memory-cache
            ttl: 5s
          # Cache unknown finalization data (eth_trace*) only for 10 seconds
          - network: "*"
            method: "*"
            finality: unknown
            empty: ignore
            connector: memory-cache
            ttl: 10s
          # Cache realtime data only for 2 seconds (eth_blockNumber, eth_gasPrice, etc) to reduce costs yet fresh enough data
          - network: "*"
            method: "*"
            finality: realtime
            empty: ignore
            connector: memory-cache
            ttl: 2s

    server:
      httpHostV4: "0.0.0.0"
      listenV6: true
      httpHostV6: "[::]"
      httpPort: 4000
      aliasing:
        rules:
          - matchDomain: "*"
            serveProject: "main"
            serveArchitecture: "evm"
            serveChain: "7055200631"

    metrics:
      enabled: true
      hostV4: "0.0.0.0"
      hostV6: "[::]"
      port: 4001

    projects:
      - id: main
        cors:
          allowedOrigins:
            - "https://*.ethpandaops.io"
          allowedMethods: 
            - "GET"
            - "POST"
            - "OPTIONS"
          allowedHeaders:
            - "Content-Type"
        upstreamDefaults:
          allowMethods:
            - "eth_blockNumber"
            - "eth_call"
            - "eth_chainId"
            - "eth_estimateGas"
            - "eth_feeHistory"
            - "eth_gasPrice"
            - "eth_getBalance"
            - "eth_getBlockByHash"
            - "eth_getBlockByNumber"
            - "eth_getBlockReceipts"
            - "eth_getBlockTransactionCountByHash"
            - "eth_getBlockTransactionCountByNumber"
            - "eth_getCode"
            - "eth_getFilterChanges"
            - "eth_getLogs"
            - "eth_getStorageAt"
            - "eth_getTransactionByBlockHashAndIndex"
            - "eth_getTransactionByBlockNumberAndIndex"
            - "eth_getTransactionByHash"
            - "eth_getTransactionCount"
            - "eth_getTransactionReceipt"
            - "eth_newBlockFilter"
            - "eth_newPendingTransactionFilter"
            - "eth_maxPriorityFeePerGas"
            - "eth_sendRawTransaction"
            - "eth_subscribe"
            - "eth_syncing"
            - "eth_uninstallFilter"
            - "eth_unsubscribe"
            - "net_listening"
            - "net_version"
            - "rpc_modules"
            - "web3_clientVersion"
            - "debug_getRawReceipts"
            - "debug_traceBlock"
            - "trace_transaction"
            - "trace_block"
        upstreams:
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-10.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-11.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-12.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-13.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-14.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-15.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-16.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-17.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-18.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-19.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-2.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-20.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-21.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-22.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-23.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-24.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-25.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-26.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-27.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-28.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-29.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-3.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-30.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-31.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-32.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-33.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-34.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-35.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-36.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-37.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-38.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-39.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-4.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-40.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-41.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-42.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-43.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-44.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-45.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-46.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-47.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-48.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-49.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-5.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-50.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-6.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-7.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-8.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-besu-9.peerdas-devnet-ssl-lighthouse-8.yolkie.xyz
