secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:OU9s2nt9BFuCWFUw8Vu4TMX0Sn/oLRVtiFv2eWXY+WxxW3BuahI=,iv:uU8NZmSRCV9um0mC1i7R/aYjIlqrDWNPEebARNSsOew=,tag:iVmytQAi3R0Vuq4jNOwL7Q==,type:str]
    username: ENC[AES256_GCM,data:ic4ME8cI,iv:aEvU4WB/hifVuDQOMKN2EP5iytNPGRyVF4im+i4sLjQ=,tag:LoiIUOgyXQZ2PFZToqq04A==,type:str]
    password: ENC[AES256_GCM,data:6++aGpBifY6+/bE0,iv:JCpRKBpbSEE0uGhGYRThnbr0u/C/eahHAlis/I6glU0=,tag:9Z9RpNiNpZ2BhZUHJ4A7Ug==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:CcV/M/jxMyO0fzKug3WAJ1JaHWxnh2KKQQ==,iv:qMZopt05jOec34OhGJ3On8WkdCyIknrFhGhxTkGgCIk=,tag:/rcOP3Du0WSNWpz9XZBKUw==,type:str]
    username: ENC[AES256_GCM,data:snM05Gj6,iv:/gCc4AAUVvXSWr1dVtBsjy31r80XG88DIbQnfdq4NDo=,tag:ZR0nC92yBcAXJKDOLzoysA==,type:str]
    password: ENC[AES256_GCM,data:a73cZGYlcCkzjkd8,iv:QtSnqcAM4KzVICVnBjYiUOoWiQX5AaLtUkkL89h/hSo=,tag:wPm78JWAO+ppc8D7ch/WOQ==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:tFE7Czh9WzmldulyNQN4w28wNkD2QzR/GTPqK3Ueb5hJ6zJv+0IlhxbCe0VK1jxibBASletGCfsXY72csIsewQ==,iv:LmQySGn5qlNS4ZMMMLX1v8BD5c9UdvpjhUuh8gAGFRk=,tag:whF3ZW5iH/nE4RaBUZe29A==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:rbNwYTDqLgRG02ocjEF+dtgxkQ2Z8A==,iv:NPZXR56YOQUFPupJlDMaV1yVCgCHpn7Va/M29ANyOLU=,tag:YKBnaJOYzAGAFUCZEkxJEg==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:zE3gL15TpXT9UyQCUDDKqX8D5GER7Yd+ayy7pWxi3g3DbWCNy2wSbkYcYlcmlz3kr+OX6bgnZ0QGEDlsu3Bhul+y12zWKAO/ZoEnZg+v3twfhH4wx3g=,iv:Y44hmZfwrqyf+1/HmFoRXpOwSmQKCehDOmMkhYyTcMs=,tag:qdZPZSy7b1vcPWIoW3DC7g==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:1rARAEsEraVA,iv:gKwwZeB7NikmTGsXGowby7aSbPSNoa/0lkNoBQ4XhXs=,tag:Q2DRMoZnmAjJvhPFRb1xHw==,type:str]
    password: ENC[AES256_GCM,data:r+oxOuaUxzz70R3n,iv:uCMNZCjXjJPvbL6FZLez701zk/dQWRzU8VHWIfgZQUM=,tag:ZsIlen4rMOHpOfbhs14nIA==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:hnypCvBAupoM,iv:kDx3HbduE6HPjsrqNngkZqQnG/nJyFu9dzB13b56vUg=,tag:YHLVHbdY4fOFVZrgF3WBRg==,type:str]
    password: ENC[AES256_GCM,data:lQFpY+TKVadsQnG7,iv:khsOBLpj/7Tj+DNS6oFHbNfRRWmQyTib3NdPQ+7rWyc=,tag:YVc5w4/JnZQLm3q54L4MdA==,type:str]
    server_address: ENC[AES256_GCM,data:cXHs4h423t/FmTQx45VLTu+x,iv:xza6nE9zy8GHpb8v2E2ysjd85tTnvtWp/wDKn+nfS7I=,tag:s9DW8pOX31/4yqMsiHPxyw==,type:str]
secret_ethstats: ENC[AES256_GCM,data:KBgFpvmtCCWn+xPeKXsdTo52LI5qd4wKw2/Jgjl/4azGbC+gz7+gUwEDLCA4Cl8Bs2wj5w8C2yV3CeNNOGktpw==,iv:3PkX63eHHV4KACDI0wZvPjSRGfoMzjar5PVA/sxJCYE=,tag:VqlcL1W2m45j3o/jzBzHWw==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:00vai6T9MoxvkFM3MJGoJjA4sL+fIxJvktfF0ypcIf2RIMg8eyE1UkT2wSxa3fY0bzLzolTaNQ4qshK+lKIu5+gzf7shPzvQbJSLe6mzs60thwa0zo1GwFJS1od0eJcjoupKdA4+liOTBHxaste6Ex92YVVfClfOadQMgLmNQdCmaMNz4pUnaAVLwqVAxsMShZen,iv:aTiWks87MxAaxz5AEeaOZQKDYYdCwtsJY60io9L0jns=,tag:BjQFIDKrXuy0jFtDhGbVIw==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:Efb0EfOB5u449W9FNTHssicKcWTXUa9BT4Zp2dfaq1IcOgApIHtX1pgVL5gEvJ4N2ccb0225viaszcJe5hhn/DDJ/P6aGVf9vyIHJz46XUVB3VYxmU7GLlB2q5hpuh1pyiVJtNeJGF25D/xUuyk0lwdplDc2HY2KQ3XfO4MIQ885RQZTjnD6nIzH6WI2cqSPuiZF7sc=,iv:SWsJ0okBJaBjNdAPIS5i6sGDWS4Z/knPE7AB9YHoUkQ=,tag:otpBG8QJ/fDg20DZS/C5Pw==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:63fypmN4IAWWz5vrWgJjppEsfHrbmg8S+4j258tRnDwQDqOgJW3orQlmqJDDM7dzgzD8DB/f46DLL69ahrVVDw==,iv:hEXOECt88Rx8z8Ya0fQDR8aHL4HyRO39yT1xXROjZbM=,tag:1N9jjBbjeid1gfNqmE1jnA==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:W6h1UIdgEmwm+wwRoXxLQQs+JvtXp47ij/tN233vdBXyhe2SbrqXB7VMUtOAE1qlILuNG7sjF07oEncb+CpnXg==,iv:7y88hUCfZos3nMhAw91V1IEYrub/uH4hTW1rygGVEUY=,tag:AUWgjZtUwvUUUpnhqS5yxg==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:3CKGfYvwtsb4Kx4RCvNo2rJHH9fCSCmyZfVI5FAjVqpVEUrKm+bf1LPvu5fJ6w4vs+QKBmCCl9Nz4QLU475rBA==,iv:gkIZx5KnTPZVxwU4Jmr1v76fH4fcKThMbgcfjsSmBPw=,tag:lf3XdrtDl7/q9HYN7rHPUg==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:jXZ9k/W+jSZ2Ft4Bw6InvlPKg11zMbnCM4qNapbh+cTVkHfhl9B0JS1+c8crvRQmRqIwD6xMlcdfLh2uVhFSEg==,iv:sIDsnlKu+HV00B2po8CKTtwpGQ6G+jnf7sPFKnTPvkQ=,tag:h3mPJjZn/99Q+oROtKJNhA==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:0y4oUod3IDtS,iv:Xtc0PfGNpP66/KpDk3/GaQj/zl4JBGg5W+tbF1cuFwE=,tag:hTA/KefajwACdYXlcrj9Iw==,type:str]
goomy_private_key: ENC[AES256_GCM,data:5nzZFcEP8ATBNuq27Do2LSJFBAWr6s4Ocfm++0qPbWsizT5epO0cl2QflGcOzIZJFGXedJeRDiDfQPbimjjuXQ==,iv:DEiEIO+KwoAfxTnpRAWawJjJid+nI9FN2NWf7Rg0ewM=,tag:2cSQD9QPiG+y1ulYBUkzfg==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:fQBhv/8JQ+B2bk4aIxUFty9PVCYqDGHBfFGssCFavOwebYLvAyRIbZHj1KMNZHh3iTBOXO3bhKMEHzsSeyG2TA==,iv:SRpaQJLRpEJ42p/1weZr6XS8rPtvk8Fbdn4zpP3qlw4=,tag:aAwObQc2BTlrsQ1eAEgTSw==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:NRx6ep+bpvcy,iv:0pkfu8epmJvo9G2NZXeKuaBY5Epm0DZEmqUh9Go5YRE=,tag:/nKJUQviRekQWu4PPyr2gQ==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:lqJZ6TyIjktKAXcY,iv:eIiR0czq+DyrBEZic9Ni138Rm1tCVyai7xYU2TDS7KI=,tag:5bCbAHk4FuTcRfA6L4cQPg==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:5WICzmvT8iCplrCL6WJ8xoUHY7R1ALcmcHc7RAkWJLfTFIQElZu96jiJq13B3f6+s/PYXj29pwsHhI3dbJDEZQ==,iv:PgpEDkHykDIbF+jeJwHSdvPuqamw6w5IGbAQ6AHdzaE=,tag:C9kf8Wluzsj6gZ3wMejHBA==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:qwSJYjH1sHbelKUk,iv:75b1cgrLbaW2LFnCA4V70Grn2nWh+fAF9lA4R/6sENk=,tag:etsTdD+OHACl4XNlhAZRXw==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:FBlJmqQZ+u5P,iv:eFpGxfhAlXJ5SzbeBeAzG/NgqxyiSbAQX1CdbMiNUvA=,tag:Ad9dfU06IdyumdNreqBSxQ==,type:str]
sops:
    lastmodified: "2025-05-23T06:58:40Z"
    mac: ENC[AES256_GCM,data:LP+qVdFCQJi3E2+7wCdSfUwMvTlwem2BmcOREuKaZjw5TBnq6Nqtp7PkgVtvYS+IAvYZe0uWs8buFyv6dzfVhVaaSRRwoQzKQjXHCWbYeHEYQqlAAAqLz7uo+FEvx6bO4+HG5iHT5NdIOrGdOcgmnUwrsuldsRYUd4Va1yPVMcA=,iv:HeFvsrDN+aGz6Rm7RXjmtOZQOGens2daVnabQXhA8Wc=,tag:pg+4AXdc2qw51M961h4P/Q==,type:str]
    pgp:
        - created_at: "2025-05-23T06:58:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQARAAhMaK8+fKTXy92fTRXlq73C2sIljVa7jxmgk81wZSbkrt
            akQAIGybgDVaHVNAoUUgNsvxlp5fpzHd9Qh/YfC/dHZeDEguKKs9tt0kpaVq/Coa
            HrThmKTcpZiTivUJ/V6zvgtjfkYRA+esNqZI0VTLBZXuvh7ywUB1EEhyXU4YDypo
            ApxQqqwATnoa7YaFy7fJI0MjwetI39hglS3a5pRbzq8g71DjD37TZlefKfFAA3n5
            RK8Yz0ItUMbAmiwBskbMO2N8QHWIUel6g5PMn+/ogFCGwfqrfrjX6fo2Hu4ctPwR
            /W3ukp844xehPSeAfhk7qVL8JKYE+DMDMKgkc+/1m71LtBns7HwFbA6LOBjOJZK6
            fDyNC+r3pjcrQjbHGwgAK9Zb1A4qTi9B7sEqH5WG6mjj8G0Wond/Gx4wby1f39o6
            a7ziTWyHFvbCmGPNAYrohm8O0toxCgNZfHcjZFjIPHpf3DehNwax/9Ghdcx4DzZs
            6dpZsapL65ZYY5o0GJEpHh/toh2RcDUD72/nyzQs6B+mHdPvLrFUbDnBKI9z04dn
            acAdRED15M38tt8ODZPt81Z8kHZaXQki4OQN3KY29k0kPs03uHTPvq3QYYa3vuDm
            PpPSjWdI2lxD51xCsuKVHUEDTvICb/qcpuu+oy3L3IC56ML4pdeCwMe5wWBDThHU
            ZgEJAhB7+ij7YUU0/3rQhwvFkRBGaVPRhV8qfgc1ksO+hVQy6DgnTCAoI7MMVbcX
            q/E8CRa6Zvf7hNZdqDef6AyHhSt0R5ggSTfG/qZKTFJm0GNtAoW+6zZlDETa32b4
            3sLnocpG1Q==
            =NH/a
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
