spamoor_container_image: "public.ecr.aws/j7m9g6q8/temporary/spamoor:v0.0.5"

spamoor_container_command: |
  blobs
  {% for host in groups['execution_node'] %}
  -h=https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.{{ host }}.{{ network_subdomain }}
  {% endfor %}
  -p={{ tx_fuzz_txs_privkey }}
  -t=1
  --throughput-increment-interval=600