spamoor_blobs_container_image: "{{ default_tooling_images.spamoor }}"
spamoor_blobs_container_name: spamoor_blobs

spamoor_rpc_urls:
  - https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.bootnode-1.{{ network_subdomain }}
  - https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-geth-1.{{ network_subdomain }}
spamoor_rpc_throughput: "10"
spamoor_scenario: "blob-combined"
spamoor_private_key: "{{ tx_fuzz_blobs_privkey }}"


spamoor_container_networks: "{{ docker_networks_shared }}"
