# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dora
    tag: fulu-support
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.pectra-devnet-ssl-4.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  name: pectra-devnet-ssl-4
  configPath: "https://config.pectra-devnet-ssl-4.yolkie.xyz/cl/config.yaml"
  validatorNamesInventory: "https://config.pectra-devnet-ssl-4.yolkie.xyz/api/v1/nodes/validator-ranges"
  proxyCount: 2
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: FRONTEND_SHOW_PEER_DAS_INFOS
      value: "true"
    - name: FRONTEND_ETH_EXPLORER_LINK
      value: "https://explorer.pectra-devnet-ssl-4.yolkie.xyz"
    - name: FRONTEND_PUBLIC_RPC_URL
      value: "https://rpc.pectra-devnet-ssl-4.yolkie.xyz"
    - name: FRONTEND_SHOW_SUBMIT_DEPOSIT
      value: "true"
    - name: FRONTEND_SHOW_SUBMIT_EL_REQUESTS
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"

  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://sunnyside:sleepyyolkie@bn.bootnode-1.pectra-devnet-ssl-4.yolkie.xyz
    name: bootnode-1
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-1.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-1
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-10.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-10
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-11.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-11
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-12.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-12
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-13.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-13
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-14.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-14
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-15.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-15
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-2.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-2
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-3.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-3
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-4.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-4
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-5.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-5
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-6.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-6
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-7.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-7
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-8.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-8
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.lighthouse-geth-9.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-9
    priority: -1
    archive: true
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-1.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-1
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-10.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-10
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-11.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-11
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-12.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-12
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-13.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-13
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-14.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-14
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-15.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-15
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-2.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-2
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-3.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-3
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-4.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-4
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-5.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-5
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-6.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-6
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-7.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-7
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-8.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-8
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.nimbus-geth-9.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-9
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-1.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-1
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-10.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-10
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-11.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-11
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-12.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-12
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-13.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-13
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-14.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-14
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-15.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-15
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-2.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-2
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-3.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-3
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-4.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-4
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-5.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-5
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-6.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-6
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-7.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-7
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-8.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-8
    priority: -1
  - url: https://sunnyside:sleepyyolkie@bn.prysm-geth-9.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-9
    priority: -1
  executionEndpoints:
  # Rpc
  - url: http://geth-teku-001:8545
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://sunnyside:sleepyyolkie@rpc.bootnode-1.pectra-devnet-ssl-4.yolkie.xyz
    name: bootnode-1
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-1.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-1
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-10.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-10
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-11.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-11
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-12.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-12
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-13.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-13
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-14.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-14
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-15.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-15
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-2.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-2
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-3.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-3
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-4.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-4
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-5.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-5
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-6.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-6
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-7.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-7
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-8.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-8
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.lighthouse-geth-9.pectra-devnet-ssl-4.yolkie.xyz
    name: lighthouse-geth-9
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-1.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-1
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-10.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-10
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-11.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-11
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-12.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-12
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-13.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-13
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-14.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-14
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-15.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-15
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-2.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-2
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-3.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-3
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-4.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-4
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-5.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-5
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-6.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-6
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-7.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-7
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-8.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-8
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.nimbus-geth-9.pectra-devnet-ssl-4.yolkie.xyz
    name: nimbus-geth-9
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-1.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-1
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-10.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-10
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-11.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-11
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-12.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-12
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-13.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-13
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-14.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-14
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-15.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-15
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-2.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-2
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-3.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-3
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-4.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-4
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-5.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-5
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-6.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-6
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-7.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-7
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-8.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-8
    priority: -1
    archive: false
  - url: https://sunnyside:sleepyyolkie@rpc.prysm-geth-9.pectra-devnet-ssl-4.yolkie.xyz
    name: prysm-geth-9
    priority: -1
    archive: false
